// Static equipment/machine dataset, grouped by body part key
// (keys match constants/index.js bodyParts exactly)

export const equipmentData = {
  chest: [
    { id: 'bench-press', name: 'Bench Press', icon: 'barbell-outline', difficulty: 'Intermediate',
      description: 'A compound barbell lift performed lying on a flat bench.',
      primaryMuscles: ['Chest', 'Triceps', 'Shoulders'], equipmentUsed: 'Barbell, Flat Bench', bodyPart: 'Chest',
      instructions: ['Lie flat on the bench with feet planted.', 'Grip the bar slightly wider than shoulder-width.', 'Lower the bar to mid-chest.', 'Press up until arms are extended.'],
      tips: ['Keep your shoulder blades retracted.', 'Maintain a slight arch in your lower back.'],
      commonMistakes: ['Bouncing the bar off the chest.', 'Flaring elbows too wide.'],
      sets: '3-4', reps: '6-10', restTime: '90-120 sec' },
    { id: 'incline-bench', name: 'Inclined Bench', icon: 'trending-up-outline', difficulty: 'Intermediate',
      description: 'Targets the upper chest using an angled bench press.',
      primaryMuscles: ['Upper Chest', 'Shoulders'], equipmentUsed: 'Barbell/Dumbbells, Incline Bench', bodyPart: 'Chest',
      instructions: ['Set bench to 30-45 degrees.', 'Press weight up from chest level.', 'Lower under control.'],
      tips: ['Avoid setting the incline too steep, or it becomes a shoulder press.'],
      commonMistakes: ['Using too much incline angle.', 'Not controlling the eccentric.'],
      sets: '3', reps: '8-12', restTime: '60-90 sec' },
    { id: 'chest-fly-machine', name: 'Chest Fly Machine', icon: 'body-outline', difficulty: 'Beginner',
      description: 'An isolation machine for chest, moving arms in an arc.',
      primaryMuscles: ['Chest'], equipmentUsed: 'Fly Machine', bodyPart: 'Chest',
      instructions: ['Sit with back flat against pad.', 'Bring handles together in front of chest.', 'Return slowly.'],
      tips: ['Squeeze at the peak contraction.'],
      commonMistakes: ['Using momentum instead of control.'],
      sets: '3', reps: '12-15', restTime: '45-60 sec' },
    { id: 'smith-machine-chest', name: 'Smith Machine', icon: 'construct-outline', difficulty: 'Beginner',
      description: 'A guided barbell on fixed vertical rails for safer pressing.',
      primaryMuscles: ['Chest', 'Triceps'], equipmentUsed: 'Smith Machine', bodyPart: 'Chest',
      instructions: ['Set bench under the bar.', 'Unrack and lower to chest.', 'Press up and re-rack.'],
      tips: ['Great for beginners lifting without a spotter.'],
      commonMistakes: ['Positioning the bench too far forward or back.'],
      sets: '3', reps: '8-12', restTime: '60-90 sec' },
    { id: 'dumbbells-chest', name: 'Dumbbells', icon: 'fitness-outline', difficulty: 'Beginner',
      description: 'Free weights allowing independent arm movement for chest presses/flys.',
      primaryMuscles: ['Chest', 'Shoulders'], equipmentUsed: 'Dumbbells', bodyPart: 'Chest',
      instructions: ['Lie on bench holding a dumbbell in each hand.', 'Press up, then lower with control.'],
      tips: ['Improves unilateral strength balance.'],
      commonMistakes: ['Letting elbows flare excessively.'],
      sets: '3', reps: '10-12', restTime: '60 sec' },
    { id: 'barbells-chest', name: 'Barbells', icon: 'remove-outline', difficulty: 'Intermediate',
      description: 'Standard barbell used for pressing and compound chest movements.',
      primaryMuscles: ['Chest', 'Triceps'], equipmentUsed: 'Barbell', bodyPart: 'Chest',
      instructions: ['Load appropriate weight.', 'Perform controlled pressing movement.'],
      tips: ['Use a spotter for heavy sets.'],
      commonMistakes: ['Uneven bar path.'],
      sets: '3-4', reps: '6-10', restTime: '90 sec' },
  ],

  back: [
    { id: 'lat-pulldown', name: 'Lat Pulldown', icon: 'arrow-down-outline', difficulty: 'Beginner',
      description: 'A cable machine exercise that mimics a pull-up motion.',
      primaryMuscles: ['Lats', 'Biceps'], equipmentUsed: 'Lat Pulldown Machine', bodyPart: 'Back',
      instructions: ['Grip bar wider than shoulders.', 'Pull down to upper chest.', 'Control the return.'],
      tips: ['Avoid leaning back excessively.'],
      commonMistakes: ['Using momentum instead of lats.'],
      sets: '3', reps: '10-12', restTime: '60 sec' },
    { id: 'seated-row', name: 'Seated Row Machine', icon: 'return-down-back-outline', difficulty: 'Beginner',
      description: 'Cable row targeting middle back and lats.',
      primaryMuscles: ['Mid Back', 'Lats', 'Biceps'], equipmentUsed: 'Row Machine', bodyPart: 'Back',
      instructions: ['Sit with feet on platform.', 'Pull handle to torso.', 'Squeeze shoulder blades, return slowly.'],
      tips: ['Keep torso upright, avoid excessive leaning.'],
      commonMistakes: ['Rounding the lower back.'],
      sets: '3', reps: '10-12', restTime: '60 sec' },
    { id: 'cable-machine-back', name: 'Cable Machine', icon: 'git-network-outline', difficulty: 'Intermediate',
      description: 'Versatile pulley system for various back exercises.',
      primaryMuscles: ['Back', 'Lats'], equipmentUsed: 'Cable Machine', bodyPart: 'Back',
      instructions: ['Attach appropriate handle.', 'Perform pulling motion targeting back.'],
      tips: ['Adjust pulley height per exercise.'],
      commonMistakes: ['Using too much arm instead of back.'],
      sets: '3', reps: '10-15', restTime: '45-60 sec' },
    { id: 'assisted-pullup', name: 'Assisted Pull-up', icon: 'trending-up-outline', difficulty: 'Beginner',
      description: 'Machine that counterbalances bodyweight for easier pull-ups.',
      primaryMuscles: ['Lats', 'Biceps'], equipmentUsed: 'Assisted Pull-up Machine', bodyPart: 'Back',
      instructions: ['Set counterweight.', 'Kneel on platform, grip handles.', 'Pull chin above bar.'],
      tips: ['Gradually reduce assistance over time.'],
      commonMistakes: ['Using too much assistance for too long.'],
      sets: '3', reps: '8-10', restTime: '60-90 sec' },
    { id: 'pullup-dip-station', name: 'Pull-up & Dip Station', icon: 'git-merge-outline', difficulty: 'Advanced',
      description: 'A freestanding rack for bodyweight pull-ups and dips.',
      primaryMuscles: ['Back', 'Chest', 'Triceps'], equipmentUsed: 'Pull-up/Dip Station', bodyPart: 'Back',
      instructions: ['Grip bar, hang fully.', 'Pull chin over the bar.', 'Lower under control.'],
      tips: ['Engage core to prevent swinging.'],
      commonMistakes: ['Using momentum/kipping.'],
      sets: '3-4', reps: '6-10', restTime: '90 sec' },
  ],

  shoulders: [
    { id: 'shoulder-press', name: 'Shoulder Press', icon: 'arrow-up-outline', difficulty: 'Intermediate',
      description: 'Overhead pressing movement for deltoid development.',
      primaryMuscles: ['Shoulders', 'Triceps'], equipmentUsed: 'Barbell/Dumbbells/Machine', bodyPart: 'Shoulders',
      instructions: ['Start weight at shoulder height.', 'Press overhead until arms extend.', 'Lower with control.'],
      tips: ['Avoid arching the lower back excessively.'],
      commonMistakes: ['Flaring elbows too far back.'],
      sets: '3', reps: '8-12', restTime: '60-90 sec' },
    { id: 'dumbbells-shoulders', name: 'Dumbbells', icon: 'fitness-outline', difficulty: 'Beginner',
      description: 'Free weights for lateral raises, presses, and isolation work.',
      primaryMuscles: ['Shoulders'], equipmentUsed: 'Dumbbells', bodyPart: 'Shoulders',
      instructions: ['Choose an appropriate movement (raise/press).', 'Perform with controlled tempo.'],
      tips: ['Lighter weight with strict form beats heavy swinging.'],
      commonMistakes: ['Using momentum on lateral raises.'],
      sets: '3', reps: '12-15', restTime: '45-60 sec' },
    { id: 'barbells-shoulders', name: 'Barbells', icon: 'remove-outline', difficulty: 'Intermediate',
      description: 'Used for overhead press and upright rows.',
      primaryMuscles: ['Shoulders'], equipmentUsed: 'Barbell', bodyPart: 'Shoulders',
      instructions: ['Grip bar shoulder-width.', 'Press or row per chosen exercise.'],
      tips: ['Warm up shoulders thoroughly before heavy pressing.'],
      commonMistakes: ['Excessive back arch during presses.'],
      sets: '3', reps: '8-10', restTime: '90 sec' },
    { id: 'cable-machine-shoulders', name: 'Cable Machine', icon: 'git-network-outline', difficulty: 'Intermediate',
      description: 'Provides constant tension for lateral/front raises.',
      primaryMuscles: ['Shoulders'], equipmentUsed: 'Cable Machine', bodyPart: 'Shoulders',
      instructions: ['Attach handle at low pulley.', 'Raise arm to shoulder height.', 'Lower slowly.'],
      tips: ['Constant cable tension improves time-under-tension.'],
      commonMistakes: ['Using shoulder shrug instead of raise.'],
      sets: '3', reps: '12-15', restTime: '45 sec' },
  ],

  'upper arms': [
    { id: 'preacher-curl', name: 'Preacher Curl Machine', icon: 'barbell-outline', difficulty: 'Beginner',
      description: 'Isolates the biceps by fixing the upper arm against a pad.',
      primaryMuscles: ['Biceps'], equipmentUsed: 'Preacher Curl Machine', bodyPart: 'Upper Arms',
      instructions: ['Rest arms on the pad.', 'Curl weight up.', 'Lower under control.'],
      tips: ['Avoid locking elbows fully at the bottom.'],
      commonMistakes: ['Using momentum/swinging.'],
      sets: '3', reps: '10-12', restTime: '45-60 sec' },
    { id: 'cable-machine-arms', name: 'Cable Machine', icon: 'git-network-outline', difficulty: 'Beginner',
      description: 'Great for tricep pushdowns and cable curls.',
      primaryMuscles: ['Biceps', 'Triceps'], equipmentUsed: 'Cable Machine', bodyPart: 'Upper Arms',
      instructions: ['Attach handle/bar.', 'Perform curl or pushdown motion.'],
      tips: ['Keep elbows pinned to your sides.'],
      commonMistakes: ['Letting elbows drift forward.'],
      sets: '3', reps: '12-15', restTime: '45 sec' },
    { id: 'dumbbells-arms', name: 'Dumbbells', icon: 'fitness-outline', difficulty: 'Beginner',
      description: 'Used for bicep curls and tricep extensions.',
      primaryMuscles: ['Biceps', 'Triceps'], equipmentUsed: 'Dumbbells', bodyPart: 'Upper Arms',
      instructions: ['Curl or extend with controlled form.'],
      tips: ['Alternate arms to maintain focus.'],
      commonMistakes: ['Swinging the weight.'],
      sets: '3', reps: '10-12', restTime: '45-60 sec' },
    { id: 'barbells-arms', name: 'Barbells', icon: 'remove-outline', difficulty: 'Intermediate',
      description: 'Used for barbell curls and close-grip presses.',
      primaryMuscles: ['Biceps', 'Triceps'], equipmentUsed: 'Barbell', bodyPart: 'Upper Arms',
      instructions: ['Grip bar shoulder-width.', 'Curl or press per exercise.'],
      tips: ['Keep wrists neutral.'],
      commonMistakes: ['Excessive body swing (cheat curls).'],
      sets: '3', reps: '8-10', restTime: '60 sec' },
  ],

  'lower arms': [
    { id: 'dumbbells-lower-arms', name: 'Dumbbells', icon: 'fitness-outline', difficulty: 'Beginner',
      description: 'Used for wrist curls and forearm isolation.',
      primaryMuscles: ['Forearms'], equipmentUsed: 'Dumbbells', bodyPart: 'Lower Arms',
      instructions: ['Rest forearm on a bench.', 'Curl wrist up and down.'],
      tips: ['Use light weight, high reps.'],
      commonMistakes: ['Using too much weight, limiting range.'],
      sets: '3', reps: '15-20', restTime: '30-45 sec' },
    { id: 'cable-machine-lower-arms', name: 'Cable Machine', icon: 'git-network-outline', difficulty: 'Beginner',
      description: 'Used for cable wrist curls and grip work.',
      primaryMuscles: ['Forearms'], equipmentUsed: 'Cable Machine', bodyPart: 'Lower Arms',
      instructions: ['Attach a bar at low pulley.', 'Curl wrists toward you.'],
      tips: ['Keep movement slow and controlled.'],
      commonMistakes: ['Rushing through reps.'],
      sets: '3', reps: '15-20', restTime: '30-45 sec' },
  ],

  'upper legs': [
    { id: 'leg-press', name: 'Leg Press', icon: 'car-outline', difficulty: 'Beginner',
      description: 'A machine that lets you press weight away using your legs.',
      primaryMuscles: ['Quads', 'Glutes', 'Hamstrings'], equipmentUsed: 'Leg Press Machine', bodyPart: 'Upper Legs',
      instructions: ['Sit with feet shoulder-width on platform.', 'Lower until knees reach ~90°.', 'Press back up.'],
      tips: ['Do not lock knees fully at the top.'],
      commonMistakes: ['Letting knees cave inward.'],
      sets: '3-4', reps: '10-15', restTime: '60-90 sec' },
    { id: 'leg-extension', name: 'Leg Extension', icon: 'trending-up-outline', difficulty: 'Beginner',
      description: 'Isolation machine for the quadriceps.',
      primaryMuscles: ['Quads'], equipmentUsed: 'Leg Extension Machine', bodyPart: 'Upper Legs',
      instructions: ['Sit with pad on shins.', 'Extend legs fully.', 'Lower slowly.'],
      tips: ['Avoid swinging weight up.'],
      commonMistakes: ['Using momentum.'],
      sets: '3', reps: '12-15', restTime: '45-60 sec' },
    { id: 'hamstring-curl', name: 'Hamstring Curl', icon: 'trending-down-outline', difficulty: 'Beginner',
      description: 'Isolation machine for hamstrings.',
      primaryMuscles: ['Hamstrings'], equipmentUsed: 'Hamstring Curl Machine', bodyPart: 'Upper Legs',
      instructions: ['Lie face down, pad behind ankles.', 'Curl heels toward glutes.', 'Lower slowly.'],
      tips: ['Avoid lifting hips off the pad.'],
      commonMistakes: ['Using momentum.'],
      sets: '3', reps: '12-15', restTime: '45-60 sec' },
    { id: 'squat-rack', name: 'Squat Rack', icon: 'construct-outline', difficulty: 'Advanced',
      description: 'A rack for performing barbell squats safely.',
      primaryMuscles: ['Quads', 'Glutes', 'Core'], equipmentUsed: 'Squat Rack, Barbell', bodyPart: 'Upper Legs',
      instructions: ['Set bar on upper back.', 'Squat down keeping chest up.', 'Drive back up.'],
      tips: ['Keep knees tracking over toes.'],
      commonMistakes: ['Rounding the lower back.'],
      sets: '4', reps: '5-8', restTime: '2-3 min' },
    { id: 'smith-machine-legs', name: 'Smith Machine', icon: 'construct-outline', difficulty: 'Beginner',
      description: 'Guided barbell useful for squats and lunges.',
      primaryMuscles: ['Quads', 'Glutes'], equipmentUsed: 'Smith Machine', bodyPart: 'Upper Legs',
      instructions: ['Position bar on shoulders.', 'Squat down and up along fixed rail.'],
      tips: ['Good for learning squat mechanics safely.'],
      commonMistakes: ['Foot placement too close to the bar.'],
      sets: '3-4', reps: '8-12', restTime: '90 sec' },
  ],

  'lower legs': [
    { id: 'calf-raise', name: 'Calf Raise', icon: 'chevron-up-outline', difficulty: 'Beginner',
      description: 'Machine or standing exercise targeting the calves.',
      primaryMuscles: ['Calves'], equipmentUsed: 'Calf Raise Machine', bodyPart: 'Lower Legs',
      instructions: ['Stand with balls of feet on platform.', 'Raise heels as high as possible.', 'Lower below platform level.'],
      tips: ['Pause briefly at the top for peak contraction.'],
      commonMistakes: ['Using a limited range of motion.'],
      sets: '3-4', reps: '15-20', restTime: '30-45 sec' },
    { id: 'smith-machine-lower-legs', name: 'Smith Machine', icon: 'construct-outline', difficulty: 'Beginner',
      description: 'Can be used for standing calf raises with added load.',
      primaryMuscles: ['Calves'], equipmentUsed: 'Smith Machine', bodyPart: 'Lower Legs',
      instructions: ['Position bar on shoulders, toes on a raised block.', 'Raise and lower heels.'],
      tips: ['Use a slow eccentric for better calf activation.'],
      commonMistakes: ['Bouncing at the bottom.'],
      sets: '3', reps: '15-20', restTime: '30-45 sec' },
  ],

  cardio: [
    { id: 'treadmill', name: 'Treadmill', icon: 'walk-outline', difficulty: 'Beginner',
      description: 'A motorized belt for walking, jogging, or running indoors.',
      primaryMuscles: ['Cardiovascular System', 'Legs'], equipmentUsed: 'Treadmill', bodyPart: 'Cardio',
      instructions: ['Set desired speed/incline.', 'Maintain steady pace or interval pattern.'],
      tips: ['Use handrails only for balance, not support.'],
      commonMistakes: ['Overstriding at high speeds.'],
      sets: '1', reps: '20-40 min', restTime: 'N/A' },
    { id: 'spin-bike', name: 'Spin Bike', icon: 'bicycle-outline', difficulty: 'Beginner',
      description: 'Stationary bike for low-impact cardio and interval training.',
      primaryMuscles: ['Cardiovascular System', 'Quads', 'Calves'], equipmentUsed: 'Spin Bike', bodyPart: 'Cardio',
      instructions: ['Adjust seat height.', 'Pedal at target resistance/cadence.'],
      tips: ['Keep a slight bend in the knee at full extension.'],
      commonMistakes: ['Seat set too low or too high.'],
      sets: '1', reps: '20-45 min', restTime: 'N/A' },
    { id: 'elliptical', name: 'Elliptical Cross Trainer', icon: 'sync-outline', difficulty: 'Beginner',
      description: 'Low-impact full-body cardio machine.',
      primaryMuscles: ['Cardiovascular System', 'Full Body'], equipmentUsed: 'Elliptical Machine', bodyPart: 'Cardio',
      instructions: ['Grip handles, place feet on pedals.', 'Move in a smooth elliptical motion.'],
      tips: ['Engage arms via handles for a full-body effect.'],
      commonMistakes: ['Leaning too heavily on the handles.'],
      sets: '1', reps: '20-40 min', restTime: 'N/A' },
  ],

  waist: [],
  neck: [],
};

/**
 * Returns the equipment array for a given body part key.
 * Falls back to an empty array if none exists.
 */
export const getEquipmentByBodyPart = (bodyPart) => {
  if (!bodyPart) return [];
  return equipmentData[bodyPart.toLowerCase()] || [];
};